inventory_man/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("stock.urls")),
    path("auth/", include("c_user.urls")),
]

stock/urls.py
from django.urls import path
from .views import index, Inventory_view, add_inventory_view, single_category_view

app_name="stock"

urlpatterns = [
    path("", index, name="dashboard"),
    path("inventory/", Inventory_view, name="inventory"),
    path("add-inventory/", add_inventory_view, name="add-inventory"),
    path("categories/<int:pk>/", single_category_view, name="single-category"),
]

stock/models.py
from django.db import models

# Create your models here.
class Stock_category(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Shelve(models.Model):
    title = models.CharField(max_length=255, blank=False)
    description = models.TextField(blank=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class StockItem(models.Model):
    name = models.CharField(max_length=225, blank=False)
    model = models.CharField(max_length=225, blank=True)
    quantity = models.IntegerField(blank=True, default=0)
    cost_price = models.DecimalField(
        blank=True, null=True, decimal_places=2, max_digits=7, default=0.0
    )
    sale_price = models.DecimalField(
        blank=True, null=True, decimal_places=2, max_digits=7, default=0.0
    )
    last_restock = models.DateTimeField(auto_now=True)
    date_created = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(
        Stock_category, on_delete=models.CASCADE, related_name="items"
    )
    shelve = models.ForeignKey(Shelve, on_delete=models.CASCADE)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


# report (name_of_customer, number, reason, date, item)

stock/forms.py
from django import forms

class Add_inventory_form (forms.Form):
    name=forms.CharField(max_length=255)
    model = forms.CharField(max_length=255, required=False, strip=True)
    description=forms.CharField(max_length=555,required=False, strip=True)
    sale_price = forms.DecimalField(decimal_places=2, max_value=7, required=False)
    cost_price = forms.DecimalField(decimal_places=2, max_value=7, required=False)
    quantity = forms.IntegerField()
    category = forms.IntegerField(required=True)
    shelve = forms.IntegerField(required=True)

stock/views.py
from django.shortcuts import render
from django.views import generic
from .models import Stock_category, StockItem, Shelve

from .forms import Add_inventory_form

# Create your views here.
required_context = {
    "shelves": Shelve.objects.all(),
    "categories": Stock_category.objects.all(),
}


def index(request):
    context = {**required_context}
    print("hello")
    return render(request, "stock/index.html", context)


def Inventory_view(request):
    context = {
            "inventory_count":StockItem.objects.count(),
            "category_count":Stock_category.objects.count(),
            "shelve_count":Shelve.objects.count(),
            "recent_inventories":StockItem.objects.reverse()[:10],
            "inventory_out_of_stock":StockItem.objects.filter(quantity=0)
            }
    template_name = "stock/inventory.html"
    print("context", context)
    return render(request, template_name, context)


def add_inventory_view(request):
    template = "stock/add-inventory.html"
    if request.method != "POST":
        return render(request, template, {**required_context})
    print("the data", request.POST)
    p_data = Add_inventory_form(request.POST)
    if p_data.is_valid():
        print("the data", p_data.cleaned_data)
        try:
            category = Stock_category.objects.get(pk=p_data.cleaned_data["category"])
            shelve = Shelve.objects.get(pk=p_data.cleaned_data["shelve"])
            data = {**p_data.cleaned_data, "category": category, "shelve": shelve}
            StockItem.objects.create(**data)
        except (Stock_category.DoesNotExist, Shelve.DoesNotExist, Exception) as e:
            print("the error", e)
            return render(
                request,
                template,
                {
                    **required_context,
                    "status": "Invalid data submitted! Try refreshing page.",
                },
            )
        return render(
            request,
            template,
            {**required_context, **p_data.cleaned_data, "status": "200"},
        )
    return render(request, template, {**required_context, "status": p_data.errors})


def single_category_view(request):
    context = {**required_context}
    return render(request, "stock/categories.html", context)

stock/templates/base/layout.html
{%load static%}
<html>
	<head>
		<meta name="author" content="Opoku Shadrack" />
		<meta name="viewport" content="initial-scale=1.0" />
		<title>In-man {%block title %} {%endblock%}</title>
		<link
			href="{% static 'bootstrap-5.3.2-dist/css/bootstrap.min.css' %}"
			rel="stylesheet"
		/>
		<link
			href="{%static 'css/header.css'%}"
			rel="stylesheet"
			type="text/css"
		/>
		<link
			href="{% static 'css/layout.css' %}"
			rel="stylesheet"
			type="text/css"
		/>
		{%block head%}{%endblock%}

		<script src="{% static 'js/chart.umd.js' %}"></script>
	</head>
	<body>
		<header>
			<!-- header -->
			<nav class="navbar navbar-expand-lg bg-dark">
				<div class="container-fluid ">
					<a class="navbar-brand  text-light" href="{%url 'stock:dashboard'%}"
						>Stock-man</a
					>
					<button
						class="navbar-toggler   text-light bg-light"
						type="button"
						data-bs-toggle="collapse"
						data-bs-target="#navbarSupportedContent"
						aria-controls="navbarSupportedContent"
						aria-expanded="false"
						aria-label="Toggle navigation"
					>
						<span class="navbar-toggler-icon"></span>
					</button>
					<div
						class="collapse navbar-collapse"
						id="navbarSupportedContent"
					>
						<ul class="navbar-nav me-auto mb-2 mb-lg-0">
							<li class="nav-item">
								<a
									class="nav-link  text-light active"
									aria-current="page"
									href="{%url 'stock:dashboard'%}"
									>Dashboard</a
								>
							</li>
							<li class="nav-item dropdown">
								<a
									class="nav-link dropdown-toggle   text-light"
									href="#"
									role="button"
									data-bs-toggle="dropdown"
									aria-expanded="false"
								>
									Inventory
								</a>
								<ul class="dropdown-menu">
									<li>
										<a class="dropdown-item " href="{%url 'stock:inventory'%}"
											>Overview</a
										>
									</li>
									<li>
										<a class="dropdown-item" href="#"
											>Categories</a
										>
									</li>
									<li>
										<a class="dropdown-item" href="#"
											>Shelves</a
										>
									</li>
									<li><hr class="dropdown-divider" /></li>
									<li>
										<a class="dropdown-item" href="#"
											>Add inventory</a
										>
									</li>
								</ul>
							</li>


							<li class="nav-item dropdown">
								<a
									class="nav-link dropdown-toggle  text-light"
									href="#"
									role="button"
									data-bs-toggle="dropdown"
									aria-expanded="false"
								>
									Sales (Issued)
								</a>
								<ul class="dropdown-menu">
									<li>
										<a class="dropdown-item" href="#"
											>Overview</a
										>
									</li>
									<li>
										<a class="dropdown-item" href="#"
											>Issue item</a
										>
									</li>
									<li>
										<a class="dropdown-item" href="#"
											>Create invoice</a
										>
									</li>

									<li><hr class="dropdown-divider" /></li>
									<li>
										<a class="dropdown-item" href="#"
											>Report spoilage</a
										>
									</li>
								</ul>
							</li>

							<li class="nav-item dropdown">
								<a
									class="nav-link dropdown-toggle  text-light"
									href="#"
									role="button"
									data-bs-toggle="dropdown"
									aria-expanded="false"
								>
								Account
								</a>
								<ul class="dropdown-menu">
									<li>
										<a class="dropdown-item" href="#"
											>Change password</a
										>
									</li>
									<li>
										<a class="dropdown-item" href="#"
											>Logout</a
										>
									</li>
								</ul>
							</li>
						</ul>
						<form class="d-flex" role="search">
							<input
								class="form-control me-2"
								type="search"
								placeholder="Search"
								aria-label="Search"
							/>
							<button
								class="btn btn-outline-success"
								type="submit"
							>
								Search
							</button>
						</form>
					</div>
				</div>
			</nav>
		</header>

		<br />
		<content> {%block content%} {%endblock%} </content>
		<script src="{%static 'js/jquery-3.6.0.js' %}"></script>
		<script
			src="{% static 'bootstrap-5.3.2-dist/js/bootstrap.bundle.min.js' %}"
			crossorigin="anonymous"
		></script>
		<script
			src="{% static 'js/index.js' %}"
			type="text/javascript"
		></script>
		{% block scriptTag %}{% endblock %}
	</body>
</html>