inventory_man/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("stock.urls")),
    path("auth/", include("c_user.urls")),
]

stock/urls.py
from django.urls import path
from .views import index, Inventory_view, add_inventory_view, single_category_view

app_name="stock"

urlpatterns = [
    path("", index, name="dashboard"),
    path("inventory/", Inventory_view, name="inventory"),
    path("add-inventory/", add_inventory_view, name="add-inventory"),
    path("categories/<int:pk>/", single_category_view, name="single-category"),
]

stock/models.py
from django.db import models

# Create your models here.
class Stock_category(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Shelve(models.Model):
    title = models.CharField(max_length=255, blank=False)
    description = models.TextField(blank=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class StockItem(models.Model):
    name = models.CharField(max_length=225, blank=False)
    model = models.CharField(max_length=225, blank=True)
    quantity = models.IntegerField(blank=True, default=0)
    cost_price = models.DecimalField(
        blank=True, null=True, decimal_places=2, max_digits=7, default=0.0
    )
    sale_price = models.DecimalField(
        blank=True, null=True, decimal_places=2, max_digits=7, default=0.0
    )
    last_restock = models.DateTimeField(auto_now=True)
    date_created = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(
        Stock_category, on_delete=models.CASCADE, related_name="items"
    )
    shelve = models.ForeignKey(Shelve, on_delete=models.CASCADE)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


# report (name_of_customer, number, reason, date, item)

stock/forms.py
from django import forms

class Add_inventory_form (forms.Form):
    name=forms.CharField(max_length=255)
    model = forms.CharField(max_length=255, required=False, strip=True)
    description=forms.CharField(max_length=555,required=False, strip=True)
    sale_price = forms.DecimalField(decimal_places=2, max_value=7, required=False)
    cost_price = forms.DecimalField(decimal_places=2, max_value=7, required=False)
    quantity = forms.IntegerField()
    category = forms.IntegerField(required=True)
    shelve = forms.IntegerField(required=True)

stock/views.py
from django.shortcuts import render
from django.views import generic
from .models import Stock_category, StockItem, Shelve

from .forms import Add_inventory_form

# Create your views here.
required_context = {
    "shelves": Shelve.objects.all(),
    "categories": Stock_category.objects.all(),
}


def index(request):
    context = {**required_context}
    print("hello")
    return render(request, "stock/index.html", context)


def Inventory_view(request):
    context = {
            "inventory_count":StockItem.objects.count(),
            "category_count":Stock_category.objects.count(),
            "shelve_count":Shelve.objects.count(),
            "recent_inventories":StockItem.objects.reverse()[:10],
            "inventory_out_of_stock":StockItem.objects.filter(quantity=0)
            }
    template_name = "stock/inventory.html"
    print("context", context)
    return render(request, template_name, context)


def add_inventory_view(request):
    template = "stock/add-inventory.html"
    if request.method != "POST":
        return render(request, template, {**required_context})
    print("the data", request.POST)
    p_data = Add_inventory_form(request.POST)
    if p_data.is_valid():
        print("the data", p_data.cleaned_data)
        try:
            category = Stock_category.objects.get(pk=p_data.cleaned_data["category"])
            shelve = Shelve.objects.get(pk=p_data.cleaned_data["shelve"])
            data = {**p_data.cleaned_data, "category": category, "shelve": shelve}
            StockItem.objects.create(**data)
        except (Stock_category.DoesNotExist, Shelve.DoesNotExist, Exception) as e:
            print("the error", e)
            return render(
                request,
                template,
                {
                    **required_context,
                    "status": "Invalid data submitted! Try refreshing page.",
                },
            )
        return render(
            request,
            template,
            {**required_context, **p_data.cleaned_data, "status": "200"},
        )
    return render(request, template, {**required_context, "status": p_data.errors})


def single_category_view(request):
    context = {**required_context}
    return render(request, "stock/categories.html", context)

stock/templates/stock/add-inventory.html
{% extends "base/layout.html"%} {% block title %} Add inventory {% endblock %}
{% block content %}
<div class="container d-flex justify-content-center">
	<div class="p-3 mw-50">
		{% if status %}
			{% if status == "200"%}
				<div class="alert alert-success alert-dismissible">
					<button type="button" class="close" data-dismiss="alert">&times;</button>
					<strong>Inventory added</strong>successfully.
				</div>
			{% else %}
				<div class="alert alert-danger alert-dismissible">
					<button class="close" data-dismiss="alert" type="button">&times;</button>
					<strong>Failed</strong> to add inventory item.
					{{ status }}
				</div>
			{% endif %}
		{% endif %}
		<form method="POST" action="{% url 'stock:add-inventory' %}">
			{% csrf_token %}
			<div class="form-group">
				<label for="item-name">Item name</label>
				<input
					type="text"
					class="form-control"
					id="item-name"
					placeholder="samsung"
					name="name"
					required
				/>
			</div>
			<div class="form-group">
				<label for="item-model">Item model</label>
				<input
					type="text"
					class="form-control"
					id="item-model"
					placeholder="galaxy s5"
					name="model"
				/>
			</div>
			<div class="row">
				<div class="form-group col-8">
					<label for="Quantity">Quantity</label>
					<input
						type="number"
						class="form-control"
						id="Quantity"
						placeholder=""
						required
						value="0"
						name="quantity"
					/>
				</div>
				<div class="form-check col-4">
					<br />
					<!--
					<input
						type="checkbox"
						class="form-check-input"
						id="exampleCheck1"
					/>
					<label class="form-check-label" for="exampleCheck1"
						>Check me out</label
					>
					-->
				</div>
			</div>
			<div class="row">
				<div class="form-group col-6">
					<label for="cost-price">Stock price</label>
					<input
						type="number"
						class="form-control"
						id="cost-price"
						placeholder="eg. Ghc12"
						name="cost-price"
					/>
				</div>
				<div class="form-check col-6">
					<label for="selling-price">Selling price</label>
					<input
						type="number"
						class="form-control"
						id="selling-price"
						placeholder="eg. Ghc15"
						name="sale-price"
					/>
				</div>
			</div>

			<div class="row">
				<div class="form-group col-6">
					<label for="shelve">Shelve name</label>
					<select class="form-control" id="shelve" {%if not shelves%}disabled{%endif%} name="shelve">
						{%if shelves%} {%for shelve in shelves%}
						<option value="{{ shelve.id }}">
							{{shelve.title}}
						</option>
						{%endfor%} {%endif%}
					</select>
				</div>
				<div class="form-group col-6">
					<label for="category">Category</label>
					<select class="form-control" id="category" name="category">
						{% for category in categories %}
						<option value="{{category.id}}">
							{{ category.title }} category
						</option>
						{% endfor %}
					</select>
				</div>
			</div>
			<button type="submit" class="btn btn-primary">Submit</button>
		</form>
	</div>
</div>
{% endblock %}

stock/templates/stock/categories.html
{% extends "base/layout.html" %}
{% block title %}
	category {{ category.id }}
{% endblock %}

{% block content %}
<div clas>
	{{ category.id }}
</div>
{% endblock %}

stock/templates/stock/index.html
{%extends 'base/layout.html'%}
{%block title%} test titltl {%endblock%}
{%block content%} 
<div class="container">
	<div class="row">
		<!--main-->
		<div class="col-md-8">
			<div class="card card-container">
				<!-- chart -->
				<canvas id="inventory_level_ctx" width="80%" height="50"></canvas>
			</div>
			<br/>
			<br/>
			<div class="row">
				<div class=" col-7 card card-container">
					<!-- chart -->
					<canvas id="inventory-type-rate" width="12" height="20"></canvas>
				</div>

				<div class="card col-5 card-container">
					<!-- chart -->
					<h1>22</h1>
					<p>number of stock</p>
				</div>
			</div>
		</div>

		<aside class="col-md-4">
			<div class="card card-container">
				hellow
			</div>
		</aside>
	</div>
</div>
{% load static %}
<script src="{% static 'js/dashboard/charts.js' %}"></script>
{%endblock%}

stock/templates/stock/inventory.html
{%extends 'base/layout.html'%} {%block title%}Inventory overview{%endblock%}
{%block content%}

<div class="container" style="">
	<div class="p-2 card">
	 	<div class="d-flex justify-content-start">
			<a href="{%url 'stock:dashboard'%}" class="link text-dark"> home/</a>
			<a href="#" class="link text-dark"> &nbsp;inventory-overview/</a>
		</div>
	</div>

	<div class="my-2 row gy-5">
		<div class="col-6 col-md-4" style="height: 12rem">
			<ul class="list-group">
				<li class="bg-dark bg-opacity-75 text-white list-group-item">
					<br />
					<p class="text-center fs-1">{{ inventory_count }}</p>
					<p class="text-center">Total number of inventory</p>
				</li>
				<li class="list-group-item">All inventory</li>
			</ul>
		</div>

		<div class="col-6 col-md-4" style="height: 12rem">
			<ul class="list-group">
				<li class="bg-dark bg-opacity-75 text-white list-group-item">
					<br />
					<p class="text-center fs-1">{{ category_count }}</p>
					<p class="text-center">Total number of Category</p>
				</li>
				<li class="list-group-item">All category</li>
			</ul>
		</div>

		<div
			class="col-6 col-md-4"
			style="height: 12rem"
		>
			<ul class="list-group">
				<li class="bg-dark bg-opacity-75 text-white list-group-item">
					<br />
					<p class="text-center fs-1">{{ shelve_count }}</p>
					<p class="text-center">Total number of shelves</p>
				</li>
				<li class="list-group-item">All shelves</li>
			</ul>
		</div>

	</div>

		<div class="my-5 ">
			<div class="card p-2">
				<h5>Quick acions</h3>
				<div>
				<button type="button" class="btn btn-secondary m-2">Add new inventory</button>
				<button type="button" class="btn btn-secondary m-2">Add customer</button>
				<button type="button" class="btn btn-secondary m-2">Restock existing inventory</button>
				<button type="button" class="btn btn-secondary m-2">Create new category</button>
				<button type="button" class="btn btn-secondary m-2">Create new new shelve</button>
				<button type="button" class="btn btn-secondary m-2">show all transcation logs</button>
				</div>
			</div>
		</div>

	<div class="row">
		<div class="col-12 col-md-8 ">
			<div class="card p-4">
				<h4>Recent invetories</h4>
				<table class="table">
					<thead>
						<tr class="table-dark">
							<td>Item name</td>
							<td>Category</td>
							<td>Shelve</td>
							<td>Quantity</td>
						</tr>
					</thead>
					<tbody>
						{% for inventory in recent_inventories %}
							<tr>
								<td>{{ inventory.name }} {{ inventory.model }}</td >
								<td>{{ inventory.category.title }}</td>
								<td>{{ inventory.shelve.title }}</td>
								<td>{{ inventory.quantity }}</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>

		 <div class="col-12 col-md-4">
			 <div class="card p-3">
				 <h5>Inventories out of stock ({{ inventory_out_of_stock.count }})</h5>
				<table class="table">
					<thead>
						<tr class="table-dark">
							<td>Item name</td>
							<td>Quantity</td>
						</tr>
					</thead>
					<tbody>
						{% for inventory in inventory_out_of_stock %}
							<tr>
								<td>{{ inventory.name }} {{ inventory.model }}</td >
								<td>{{ inventory.quantity }}</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			 </div>
		</div>
	</div>

	<div class="card">
		<ul>
			<li>
				inventory level 
				<p>Show a line chart for the inventory level</p>
			</li>
			<li>
				number of defective stocks in a tabular form.
			</li>
		</ul>
	</div>


</div>

{%endblock%}