c_user/urls.py
from .views import login_temp_view, register_view
from django.urls import path
from django.contrib.auth.views import LoginView

app_name = "auth"

urlpatterns = [
        #path("llogin/", LoginView.as_view(template_name="c_user/login.html")),
        path("login/", login_temp_view, name="login"),
        path("register/", register_view, name="register"),
]

inventory_man/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("stock.urls")),
    path("auth/", include("c_user.urls")),
]

stock/urls.py
from django.urls import path
from .views import index, Inventory_view, add_inventory_view, single_category_view

app_name="stock"

urlpatterns = [
    path("", index, name="dashboard"),
    path("inventory/", Inventory_view, name="inventory"),
    path("add-inventory/", add_inventory_view, name="add-inventory"),
    path("categories/<int:pk>/", single_category_view, name="single-category"),
]

c_user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class Company(models.Model):
    title = models.CharField(max_length=255, unique=True)
    date_created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.title
    
class C_user(AbstractUser):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    company_admin = models.BooleanField(default=False)

    def __str__(self):
        return self.username

c_user/forms.py
from django import forms
from .models import C_user
from .models import Company

class RegisterForm(forms.Form):
    company_type =forms.CharField(max_length=255) 
    company = forms.CharField(max_length=255)
    username = forms.CharField(max_length=255)
    password= forms.CharField(max_length=255)
    re_password =  forms.CharField(max_length=255)
    email = forms.EmailField()


class LoginForm(RegisterForm):
    company = forms.IntegerField()
    email = forms.CharField(required=False)
    company_type = forms.CharField(required=False)
    re_password = forms.CharField(required=False)

c_user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.utils.html import json_script
from .forms import RegisterForm, LoginForm
from .models import Company, C_user


def login_temp_view(request):
    template = "./c_user/login.html"
    context = {"err": "", "companies": Company.objects.all()}
    print("companies", context)
    if request.method == "POST":
        print("its a post", request.POST)
        post_data = LoginForm(request.POST)
        if post_data.is_valid():
            cred_ = {
                "username": post_data.cleaned_data["username"],
                "password": post_data.cleaned_data["password"],
            }
            # check the user credentials
            the_user = authenticate(request, **cred_)
            # when there is no user.
            if not the_user:
                context["err"] = "Invalid username or password!"
                return render(request, template, {**context})
            # login the user
            login(request, the_user)
            return redirect("stock:dashboard")
        # invalid post data
        context["err"] = post_data.errors
        return render(request, template, {**context})
    # get request
    print("its a get request.")
    return render(request, template, context)


def register_view(request):
    context = {"companies": Company.objects.all()}
    template = "./c_user/register.html"
    if not request.method == "POST":
        return render(request, template)
    _form = RegisterForm(request.POST)

    if _form.is_valid():
        # print("form data ", _form.cleaned_data)
        # validation.
        valid_field, err_reason = validate_register_fields(_form.cleaned_data)
        if not valid_field:
            print("not valid field ", err_reason)
            return render(
                request,
                template,
                {**context, "register_status": err_reason},
            )
        try:
            new_company = Company.objects.create(title=_form.cleaned_data["company"])
            u = C_user.objects.create(
                username=_form.cleaned_data["username"],
                email=_form.cleaned_data["email"],
                company=new_company,
            )
            u.set_password(_form.cleaned_data["password"])
            u.save()
        except Exception as e:
            print("error while registering ", e)
            return render(
                request,
                template,
                {**context, "register_status": "An unknown error while registering"},
            )

        return render(request, template, {**context, "register_status": 201})
    print("form errors ", _form.errors)
    return render(request, template, {**context, "register_status": _form.errors})


def validate_register_fields(fields):
    state = True
    reason = None
    if Company.objects.filter(title=fields["company"]).exists():
        return False, "Company name already exists."
    if fields["password"] != fields["re_password"]:
        return False, "Passwords do no match!"
    return state, reason

c_user/templates/c_user/base.html
{%load static%}
<html>
	<head>
		<meta name="author" content="Opoku Shadrack" />
		<meta name="viewport" content="initial-scale=1.0" />
		<title>In-man {%block title %} {%endblock%}</title>
		<link
			href="{% static 'bootstrap-5.3.2-dist/css/bootstrap.min.css' %}"
			rel="stylesheet"
		/>
		<link
			href="{%static 'css/header.css'%}"
			rel="stylesheet"
			type="text/css"
		/>
		<link
			href="{% static 'css/layout.css' %}"
			rel="stylesheet"
			type="text/css"
		/>
		{%block head%}{%endblock%}

		<script src="{% static 'js/chart.umd.js' %}"></script>
	</head>
	<body>

		<content>
			{%block content%}{%endblock%}
		</content>

		<script src="{%static 'js/jquery-3.6.0.js' %}"></script>
		<script
			src="{% static 'bootstrap-5.3.2-dist/js/bootstrap.bundle.min.js' %}"
			crossorigin="anonymous"
		></script>
		{% block scripts%}{%endblock%}
	</body>
</html>

c_user/templates/c_user/login.html
{%extends './base.html'%} {%load static%} {% block title %} Login {%endblock%}
{%block head %}
<link href="{%static 'index.css'%}" rel="stylesheet" /> {%endblock%} 
{%block content%}
<div class="container">
	<div class="max-w-50 m-auto">
		{% if err != "" %}
		<div class="alert alert-danger alert-dismissible">
			<button class="btn-close" data-bs-dismiss="alert" type="button">&times;</button>
			<strong>Failed to login!</strong> 
			<br/>
			<p>Reason: 
			{{ err }}
			</p>
		</div>
		{% endif %}
		<form action="{%url 'auth:login'%}" method="POST">
			{% csrf_token %}
			<div class="form-group">
				<label for="company">Company</label>
				<select class="form-control" id="company" name="company" required>
					{% for company in companies %}
					<option value="{{company.id}}">{{ company.title }}</option>
					{% endfor %}
				</select>
			</div>
			<div class="form-group">
				<label for="username">username</label>
				<input
					type="text"
					class="form-control"
					id="username"
					placeholder="eg. John"
					name="username"
					required
				/>
			</div>
			<div class="form-group">
				<label for="password">password</label>
				<input
					type="password"
					class="form-control"
					id="password"
					placeholder=""
					name="password"
					required
				/>
			</div>
			<button type="submit" class="btn btn-primary">Submit</button>
		</form>
		<br />
		<p>
			Dont have an account? Click
			<a href="{% url 'auth:register' %}">here</a> to register
		</p>
	</div>
</div>
{%endblock%} {%block scripts%} {%endblock%}

c_user/templates/c_user/register.html
{%extends './base.html'%} {%load static%} {% block title %} Login {%endblock%}
{%block head %}
<link href="{%static 'index.css'%}" rel="stylesheet" /> {%endblock%} 
{% block content %}
<div class="container">
	<div class="max-w-50 m-auto">
		{% if register_status and register_status != 201 %}
		<div class="alert alert-danger alert-dismissible">
			<button class="btn-close" data-bs-dismiss="alert" type="button">&times;</button>
			<strong>Failed</strong> perform registeration!
			{{ register_status }}
		</div>
		{% elif register_status == 201 %}
			<div class="alert alert-success alert-dismissible">
				<button type="button" class="btn-close" data-bs-dismiss="alert">&times;</button>
				<strong>Registeration </strong>success.
			</div>
		{%endif%}
		<form action="{%url 'auth:register'%}" method="POST">
			{% csrf_token %}
		<div class="form-group">
			<label for="email">Email</label>
			<input type="email" name="email" required class="form-control" id="email"/>
		</div>
		<div class="form-group" id="existing-company">
			<label for="company">Select company</label>
			<select class="form-control" id="company" name="company_type" required>
				{% for company in companies %}
				<option value="{{company.id}}">
					{{ company.title }}
				</option>
				{% endfor %}
			</select>
		</div>
			<div class="form-group" id="new-company">
				<label for="company">company name</label>
				<input
					type="text"
					class="form-control"
					id="company"
					placeholder="company or group"
					name="company"
					required
				/>
			</div>
			<div class="form-group"> 
				<input class="" type="radio" name="company_type" value="new" id="new_company" checked aria-checked/>
				<label for="new_company">New company</label>
				<input type="radio" name="company_type" value="existing" id="existing_company"/>
				<label for="existing_company">Existing company</label>
			</div>
			<div class="form-group">
				<label for="username">username</label>
				<input
					type="text"
					class="form-control"
					id="username"
					placeholder="eg. John"
					name="username"
					required
				/>
			</div>
			<div class="form-group">
				<label for="password">password</label>
				<input
					type="password"
					class="form-control"
					id="password"
					placeholder=""
					name="password"
					required
				/>
			</div>
			<div class="form-group">
				<label for="re-password">re-password</label>
				<input
					type="password"
					class="form-control"
					id="re-password"
					placeholder=""
					name="re_password"
					required
				/>
			</div>
			<br />
			<button type="submit" class="btn btn-primary">Submit</button>
		</form>
		<br />
		<p>
			Already have an account? Click
			<a href="{% url 'auth:login' %}">here</a> to login
		</p>
	</div>
</div>
{%endblock%} {%block scripts%}
<script src="{%static 'register.js' %}"></script>
{%endblock%}